gui:
 theme:
   activeBorderColor:
     - '#ff9e64'
     - bold
   inactiveBorderColor:
     - '#7dcfff'
   optionsTextColor:
     - '#89b4fa'
   selectedLineBgColor:
     - '#313244'
   cherryPickedCommitBgColor:
     - '#45475a'
   cherryPickedCommitFgColor:
     - '#89b4fa'
   unstagedChangesColor:
     - '#f7768e'
   defaultFgColor:
     - '#cdd6f4'
   searchingActiveBorderColor:
     - '#f9e2af'
