[mgr]
ratio = [2, 2, 4]

[preview]
max_width = 1600
max_height = 900

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
